name: ubuntu-tests

on: [push, pull_request]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ cmake

    - name: Build
      run: cd tests && cmake -B build && cmake --build build

    - name: Run tests
      run: cd build && ctest

